# PROJECT DEFINITIONS 
project:
  # 2018 year Skylake
  # inputs_dir: "/home/lukas/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/inputs"
  # static_dir: "/home/lukas/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/static"
  # output_dir: "/home/lukas/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/results"

  # 2018 year mos 
  # inputs_dir: "/Users/lukas/Work/prfuk/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/inputs"
  # static_dir: "/Users/lukas/Work/prfuk/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/static"
  # output_dir: "/Users/lukas/Work/prfuk/ownCloud/Projects/GAIA_TSF/tsf_experiments/AMD_monitoring_Yxsjoberg/results"

  # 2016-2025 years 
  inputs_dir: "/media/lukas/image2/GAIA_TSF/tsf_projects/AMD_monitoring_Yxsjoberg_2016_2025/inputs"
  static_dir: "/media/lukas/image2/GAIA_TSF/tsf_projects/AMD_monitoring_Yxsjoberg_2016_2025/static"
  output_dir: "/media/lukas/image2/GAIA_TSF/tsf_projects/AMD_monitoring_Yxsjoberg_2016_2025/results"

masks:

  clean_water: "yxsjoberg_clean_water_mask.tif"
  tsf_water: "yxsjoberg_tsf_water_mask.tif"
  leak_water: "yxsjoberg_leakage_water_mask.tif"

# CLOUD MASKING 
clouds:

  method: "threshold"        # scl | threshold

  max_cloud_percent: 10

  threshold:
    blue_band_value: 1500 # 1000

  scl:
    classes: [3, 8, 9, 10]

# PRE-PROCESSING 
processing:

  rolling_window: 3
  outlier_threshold: 3

smoothing:

  window_length: 7
  polyorder: 2

# RASTER (COG) 
raster:

  driver: COG
  compression: DEFLATE
  predictor: 3
  blocksize: 512
  nodata: nan
  

# AMD SPECTRAL INDICES 
indices:
  enabled:
    - AMD_diff

  available:
    - AMD_diff
    - AMD_ratio
    - AMWI

  amd_metric: "AMD_diff"   # AMD_diff | AMD_ratio | AMWI 

# TEMPORAL FEATURES 
temporal_features:

  smooth:
    enabled: true
    type: smooth

  lag1:
    enabled: true
    type: lag
    lag: 1

  lag2:
    enabled: true
    type: lag
    lag: 2

  lag3:
    enabled: true
    type: lag
    lag: 3

  diff1:
    enabled: true
    type: diff
    order: 1

  diff2:
    enabled: true
    type: diff
    order: 2

  acc:
    enabled: true
    type: acc

  roll_mean:
    enabled: true
    type: rolling_mean
    window: 5

  roll_std:
    enabled: true
    type: rolling_std
    window: 5

monitoring: 

  reference_years: 2018 

  risk: # to be updated  

    mode: spectral # to be implemented 

    zscore_threshold: 3
    cusum_threshold: 50
    cusum_h: 3 
  
    spectral_weight: 0.40
    persistence_weight: 0.25
    instability_weight: 0.20
    acceleration_weight: 0.15

  dashboard:
    plot: true
    mask: tsf_water