
"""
GAIA_TSF Extract synthetic in-situ deformation measurements from the TRUE_LOS
GeoTIFF time series generated by synthetic_tsf_benchmark.py.

                 Ground Truth Deformation
                         │
          ┌──────────────┴──────────────┐
          │                             │
          ▼                             ▼
  Synthetic Sentinel-1 LOS      Synthetic In-situ Sensors
      (100×100 raster)            (3 monitoring points)

CSV format: 
PLATFORM,DATE,LATITUDE,LONGITUDE,LOS_DEFORMATION,QC
INSAR_SENSOR_01,2018-01-01T10:00:00Z,60.123456,15.654321,-0.8,1
INSAR_SENSOR_02,2018-01-01T10:00:00Z,60.123812,15.655104,0.5,1
INSAR_SENSOR_03,2018-01-01T10:00:00Z,60.124205,15.656212,-0.9,1
...
INSAR_SENSOR_03,2020-10-15T10:00:00Z,60.124205,15.656212,-54.3,1      

PLATFORM="OFFICE_REVIEW"
QC=0

Sensors location: 
--- 
Sensor 1 : Stable embankment
(20,20)

Sensor 2 : Stable crest
(80,80)

Sensor 3 : Hotspot centre
(75,40)
"""


from pathlib import Path
from datetime import datetime
import re

import numpy as np
import pandas as pd
import rasterio
from pyproj import Transformer


# CONFIGURATION
PROJECT_DIR = Path(
    "/Users/lukas/Work/prfuk/ownCloud/Projects/GAIA_TSF/"
    "tsf_experiments/synthetic_tsf_deformation"
)

INPUT_DIR = PROJECT_DIR / "inputs"
TRUE_LOS_DIR = INPUT_DIR / "true_los"
OUTPUT_CSV = INPUT_DIR / "in_situ_deformation.csv"

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# Gaussian sensor noise (1 mm)
SENSOR_NOISE_STD = 1.0  # mm

# Probability of sensor failure
FAILURE_PROBABILITY = 0.03

# Sensor locations (col, row)
SENSORS = {
    "INSAR_SENSOR_01": (20, 20),   # stable
    "INSAR_SENSOR_02": (80, 80),   # stable
    "INSAR_SENSOR_03": (75, 40),   # hotspot centre
}


def parse_date(filename: str) -> datetime:
    """Extract YYYYMMDD from filenames like TRUE_LOS_20180101.tif."""
    m = re.search(r"(20\d{6})", filename)
    if not m:
        raise ValueError(f"Cannot parse date from {filename}")
    return datetime.strptime(m.group(1), "%Y%m%d")


def pixel_to_latlon(transform, crs, row, col):
    """Convert raster pixel to WGS84 latitude/longitude."""
    x, y = rasterio.transform.xy(transform, row, col, offset="center")
    transformer = Transformer.from_crs(crs, "EPSG:4326", always_xy=True)
    lon, lat = transformer.transform(x, y)
    return lat, lon


def main():

    files = sorted(TRUE_LOS_DIR.glob("*.tif"))

    if not files:
        raise FileNotFoundError(
            f"No GeoTIFFs found in {TRUE_LOS_DIR}"
        )

    rows = []

    # Read CRS/transform from first image
    with rasterio.open(files[0]) as src:
        transform = src.transform
        crs = src.crs

    sensor_coords = {}

    for sensor, (col, row) in SENSORS.items():
        lat, lon = pixel_to_latlon(transform, crs, row, col)
        sensor_coords[sensor] = (lat, lon)

    for tif in files:

        acquisition = parse_date(tif.name)

        timestamp = acquisition.strftime("%Y-%m-%dT10:00:00Z")

        with rasterio.open(tif) as src:
            los = src.read(1)

        for sensor, (col, row) in SENSORS.items():

            lat, lon = sensor_coords[sensor]

            if np.random.rand() < FAILURE_PROBABILITY:

                qc = 0
                value = np.nan

            else:

                qc = 1

                # TRUE_LOS stored in metres -> convert to mm
                value = (
                    float(los[row, col]) * 1000.0
                    + np.random.normal(0.0, SENSOR_NOISE_STD)
                )

            rows.append(
                {
                    "PLATFORM": sensor,
                    "DATE": timestamp,
                    "LATITUDE": round(lat, 6),
                    "LONGITUDE": round(lon, 6),
                    "LOS_DEFORMATION (mm)": (
                        np.nan if np.isnan(value)
                        else round(value, 2)
                    ),
                    "QC": qc,
                }
            )

    df = pd.DataFrame(rows)

    OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUTPUT_CSV, index=False)

    print(f"Written {len(df)} records")
    print(f"CSV: {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
