eou:
  eodag:
    cop_dataspace:
      auth:
        credentials: &cred
          username: 'gaia.tsf.project@gmail.com'
          password: ''
  asf:
    auth:
      credentials:
        <<: *cred
sdi:
  db: &sdi_db
    host: 'postgis'
    port: 5432
    dbname: 'geodata'
    user: 'postgres'
    password: 'fevcfQBu3b3CfxFU'
  stac:
    db:
      host: 'pgstacdb'
      port: 5432
      dbname: 'stac'
      user: 'stac'
      password: 'stac'
    url: 'http://stacapi:8000'
  allowed_raster_extensions:
    - '.tif'
    - '.zip'
qcl:
  logger:
    level: DEBUG
    db:
      <<: *sdi_db
      dbname: 'logging'
storage:
  data_dir: /tmp/gaia_tsf

