FROM ghcr.io/stac-utils/pgstac:v0.9.9

USER root

RUN apt-get update && \
    apt-get install -y gdal-bin libgdal-dev

RUN apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /opt/gaia_tsf

USER postgres
