version: "3.9"

services:
  gaiatesting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gaiatesting
    restart: unless-stopped
    depends_on:
      pgstacdb:
        condition: service_healthy
      stacapi:
        condition: service_healthy
    links:
      - pgstacdb
    volumes:
      - ../subsystems:/opt/gaia_tsf
    networks:
      - gaia_net
    command: tail -f /dev/null

  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fevcfQBu3b3CfxFU
      POSTGRES_DB: postgres
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U stac" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - gaia_net

  pgstacdb:
    build:
      context: .
      dockerfile: Dockerfile.pgstacdb
    container_name: pgstacdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: stac
      POSTGRES_PASSWORD: stac
      POSTGRES_DB: stac
      LOCALSTACK: "1"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    #   oom_kill_disable: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: 100G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stac" ]
      interval: 10s
      # timeout: 5s
      retries: 30
    ports:
      - "7432:5432"
    volumes:
      - pgstac_data:/var/lib/postgresql/data
      - ../subsystems:/opt/gaia_tsf
    networks:
      - gaia_net
    depends_on:
      localstack:
        condition: service_healthy
    # links:
    #   - localstack

  localstack:
    image: localstack/localstack:4.13.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    #   - POSTGRES_USER=stac
    #   - POSTGRES_PASSWORD=stac
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U stac" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    networks:
      - gaia_net

  stacapi:
    build:
      context: .
      dockerfile: Dockerfile.stacapi
    container_name: stacapi
    restart: unless-stopped
    depends_on:
      pgstacdb:
        condition: service_healthy
    links:
      - pgstacdb
    environment:
      # Connect to pgstac
      POSTGRES_USER: stac
      POSTGRES_PASS: stac
      POSTGRES_HOST_READER: pgstacdb
      POSTGRES_HOST_WRITER: pgstacdb
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: stac
      DATABASE_URL: postgresql://stac:stac@pgstacdb:5432/stac
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    ports:
      - "9080:8000"
    networks:
      - gaia_net

volumes:
  pgstac_data:
  pgdata:

networks:
  gaia_net:
