version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/gaia_tsf
    environment:
      LOCALSTACK: "1"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - localstack
    networks:
      - gaia_net

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - gaia_net

networks:
  gaia_net:
