# Base image from stac-fastapi
FROM ghcr.io/stac-utils/stac-fastapi:latest

# Dependencies for psycopg3
RUN apt-get update && apt-get install -y libpq-dev gcc \
    && pip install --no-cache-dir psycopg[binary] psycopg2-binary psycopg_pool \
    && rm -rf /var/lib/apt/lists/*

COPY wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh

COPY wait-migrate-start.sh /usr/local/bin/wait-migrate-start.sh
RUN chmod +x /usr/local/bin/wait-migrate-start.sh

ENTRYPOINT ["wait-migrate-start.sh"]
